### ISSUE TITLE
cube的闪灯程序

### ISSUE THREAD

**Issue by wengkai** [zucsebd2018/CortexM-Tools#20]
用CubeMX配置一个闪灯程序，能让LED闪烁。用W1配置的GNU交叉编译器编译，用W1配置的串口下载工具下载运行测试。
报告给出配置、编译、下载和运行的过程，并对CubeMX自动生成的代码做分析。

**Comment by KozakaiAya** [comment]
1

**Comment by cxycxy123** [comment]
领
