### ISSUE TITLE
mbed的echo程序

### ISSUE THREAD

**Issue by wengkai** [zucsebd2018/CortexM-Tools#23]
用mbed配置一个echo程序，能初始化第一个串口，将串口收到的内容回复回去。
源码下载后，用W1配置的GNU交叉编译器编译，用W1配置的串口下载工具下载运行测试。
报告给出配置、编译、下载和运行的过程，并对mbed自动生成的代码做分析。

**Comment by NeverMore2744** [comment]
领

**Comment by BForever** [comment]
领
