### ISSUE TITLE
Cube的API分析文档

### ISSUE THREAD

**Issue by wengkai** [zucsebd2018/CortexM-Tools#29]
给出Cube的API分析文档，能说清楚：
1. 如何初始化（包括配置时钟频率）
2. 如何配置和使用GPIO
3. 如何配置和使用串口
4. 如何配置和使用定时器
5. 如何配置和使用ADC
每一部分API函数都应自己写过代码尝试过。
小组内成员可做分工，分头尝试、编写。
除了提交文档，下周一在课内做讲解，要有slides

**Comment by shihaoL** [comment]
领

**Comment by crabfishxy** [comment]
领

**Comment by KozakaiAya** [comment]
1
